---
title: "Diana's Version VRI"
author: "Sylvia Liu"
date: "20/05/2022"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(tibble)
library(ggplot2)
library(ggthemes)
library(maps)

library(plotly) # Interactive data visualizations
library(viridis) # Color gradients
library(lubridate)

library(randomForest) 
library(ranger)       # a faster implementation of randomForest
library(caret)        # performe many machine learning models
library(broom)  # try: `install.packages("backports")` if diretly installing broom gives an error

library(reshape2) # to use melt()

library(deSolve)
library(permimp) # for calculating conditional importance in a speedy way
```

## Reading data
```{r}
covid_data <- read.csv("owid-covid-data.csv")
covid_data$date <- as.Date(covid_data$date) #, format = "%d/%m/%y")
covid <- covid_data
#head(covid_data)
```


## Vaccinations progress  

### Vaccine Roll-Out Index (vri) values for the countries

(Reference: https://www.mdpi.com/2076-393X/10/2/194/htm)

```{r}
ct_model = function(df, log.y = FALSE, model = c("logis", "asymp", "linear")) {
  # cleaning
  covid_clean = df %>% 
    filter(str_length(iso_code) <= 3) %>% 
    select(iso_code, location, date, people_vaccinated, population, aged_65_older, gdp_per_capita, cardiovasc_death_rate, population_density, hospital_beds_per_thousand, human_development_index, extreme_poverty, diabetes_prevalence, life_expectancy) %>% 
    filter(people_vaccinated != 0 & !is.na(people_vaccinated)) %>% 
    group_by(location) %>% 
    mutate(t_days = difftime(date, min(date), units = "days") %>% as.integer())
  
  # initiate r_list, to store location, r, fit, ... respectively
  r_list = list("location" = c(), "r" = c(), "fit" = c(), "y.real" = c(), "date" = c(), "t_days" = c(), "vri_data" = c(), "iso_code" = c())
  
  ## formulae, based on selected model, people_vaccinated, and log.y
  if (log.y) {
    f2 = formula(log(people_vaccinated) ~ t_days)
    # models
    if (model == "logis") {
      f1 = formula(log(people_vaccinated) ~ SSlogis(t_days, Asym, xmid, scal))
    } else if (model == "asymp") {
      f1 = formula(log(people_vaccinated) ~ SSasymp(t_days, Asym, R0, lrc))
    }
  } else {
    f2 = formula(people_vaccinated ~ t_days)
    # models
    if (model == "logis") {
      f1 = formula(people_vaccinated ~ SSlogis(t_days, Asym, xmid, scal))
    } else if (model == "asymp") {
      f1 = formula(people_vaccinated ~ SSasymp(t_days, Asym, R0, lrc))
    }
  }
  
  ## for each country (location)
  for (loc in unique(covid_clean$location)) {
    # subset cleaned data to one country
    covid_subset = covid_clean %>% filter(location == loc) %>% ungroup()
    iso = unique(covid_subset$iso_code)
    
    # try to fit model
    fit = tryCatch(
      # main function, fit asymptote regression model
      expr = {
        if (model == "linear") {
          lm(f2, data = covid_subset)
        } else {
          nls(f1, data = covid_subset)
        }
      },
      # if error, fit linear model
      error = function(error_message){
        return( lm(f2, data = covid_subset) )
      }
    )
    
    # calculate my r value, may need transform before put into vri formula
    if (class(fit) == "lm") {
      r = coef(fit)["t_days"]
    } else if (class(fit) == "nls") {
      if (model == "logis") {scal = coef(fit)["scal"]; r = 1/scal} else
        if (model == "asymp") {lrc = coef(fit)["lrc"]; r = exp(lrc)}
    }
    
    # vri = r * last people_vaccinated / end population
    last_entry = tail(covid_subset, 1)
    vri = r * last_entry$people_vaccinated / last_entry$population
    
    median_data = covid_subset %>% 
      select(-date, -t_days, -location, -iso_code, -people_vaccinated) %>% 
      summarise(across(everything(), median, na.rm = TRUE))
    
    vri_data = median_data %>% 
      mutate(iso_code = iso, location = loc, vri = vri, .before = 1)
    
    r_list[[1]] = c(r_list[[1]], loc)
    r_list[[2]] = c(r_list[[2]], r)
    r_list[[3]] = c(r_list[[3]], list(fit))
    r_list[[4]] = c(r_list[[4]], list(covid_subset$people_vaccinated))
    r_list[[5]] = c(r_list[[5]], list(covid_subset$date))
    r_list[[6]] = c(r_list[[6]], list(covid_subset$t_days))
    r_list[[7]] = c(r_list[[7]], list(vri_data))
    r_list[[8]] = c(r_list[[8]], iso)
  }
  
  ## Measuring model fitness, residual standard error (RSE).
  # for (i in seq_len(length(r_list$fit))) {
  #   if (log.y) {
  #     # residuals = real - fitted
  #     resid = r_list$y.real[[i]] - exp(fitted(r_list$fit[[i]]))
  #     # degrees of freedom = n - k - 1, k = number of parameters
  #     df = summary(r_list$fit[[i]])$df[2]
  #     r_list$rse[[i]] = (sum(resid^2)/df)^(1/2)
  #   } else {
  #     r_list$rse[[i]] = sigma(r_list$fit[[i]])
  #   }
  # }
  
  ## Measuring model fitness, Mean Absolute Scaled Error (MASE).
  # reference: https://people.duke.edu/~rnau/compare.htm
  # https://www.rdocumentation.org/packages/Metrics/versions/0.1.4/topics/mase
  for (i in seq_len(length(r_list$fit))) {
    r_list$mase[[i]] = Metrics::mase(r_list$y.real[[i]], fitted(r_list$fit[[i]]), step_size = 1)
  }
  
  return(r_list)
}
```

```{r}
# Example of use, inspect the r_list to see what's included
r_list1 = ct_model(covid_data, log.y = FALSE, model = "logis")

r_list2 = covid_data %>% 
  filter(date > ymd("2021-05-01") & date <= ymd("2021-09-01")) %>% 
  ct_model(model = "logis")

bind_rows(r_list2$vri_data)
```

