---
title: "Time Lag"
author: "David Vucic, 500505692"
date: "10/05/2022"
output: html_document
---


```{r, output = FALSE}
library(DT)
library(tidyr)
library(dplyr)
library(ggplot2)
library(plotly)
```


```{r}
# read in covid df and convert dates column to date type

covid = read.csv("/Users/davidvucic/Desktop/owid-covid-data.csv")
covid$date = as.Date(covid$date)
```

```{r}
# smoother function, returns smoothed column

Lowess <- function(data, f) {
  lowess_fit <- lowess(data, f = f)
  return(lowess_fit$y)
}
```


```{r}
# filtering to only include relevant countries 

lag_covid = lag_covid %>%
  filter(population > 1500000) %>%
  filter(gdp_per_capita > 0)
countries <- unique(lag_covid$location)
deleted <- c("Afghanistan", "Antigua and Barbuda", "Bangladesh","Benin", "Bhutan", "Bonaire Sint Eustatius and Saba", "Botswana", "Burundi","Burkina Faso", "Cameroon", "Cote d'Ivoire", "Democratic Republic of Congo", "Ethiopia","Eritrea", "Gabon", "Ghana", "Guernsey", "Guinea", "Kenya", "Kuwait", "Liberia", "Laos", "Namibia", "Nepal","Nicaragua", "Niger", "Nigeria", "Palestine", "Philippines", "Pitcairn", "Rwanda", "Saint Helena", "Senegal", "Sierra Leone", "Somalia", "South Sudan", "Sudan", "Tokelau", "Turkmenistan","Tanzania", "Uganda","Yemen", "World", "Zambia")
countries = countries[! countries %in% deleted]
#countries
```


```{r}
# select relevant columns and subset of data within a range of dates

lag_covid = select(lag_covid, "date", "location", "people_vaccinated_per_hundred", "people_fully_vaccinated_per_hundred")
start_date = "2021-02-01"
end_date = "2021-08-01"
lag_covid = lag_covid %>% filter(date >= start_date & date < end_date)
```



```{r}


# make all NA values equal to 0

lag_covid$people_vaccinated_per_hundred[is.na(lag_covid$people_vaccinated_per_hundred)] = 0
lag_covid$people_fully_vaccinated_per_hundred[is.na(lag_covid$people_fully_vaccinated_per_hundred)] = 0
```


```{r}
# Time Lag calculator function

lagValue <- function(FirstDose, SecondDose, windowsize, p)
{
  # vector for all measures of distance between matrices
  dist_vector = c()
  i = 1
  while (i <= windowsize){
    # select different subsets of matrices, calculate the distances between the 2 matrices and store the distance. This while loop will contain information for 1st vaccine lag
    FirstDose_subset <- FirstDose[i:nrow(FirstDose),1]
    SecondDose_subset <- SecondDose[1:(1 - i + nrow(SecondDose)),1]
    dist_FirstDose <- proxy::dist(t(FirstDose_subset), t(SecondDose_subset), method = "Minkowski", p = p)
    dist_vector = c(dist_vector, dist_FirstDose)
    i = i + 1
  }
  
  
  j = 1
  while (j <= windowsize){
    # select different subsets of matrices, calculate the distances between the 2 matrices and store the distance. This while loop will contain information for 2nd vaccine lag
    FirstDose_subset1 <- FirstDose[1:(1 - j + nrow(FirstDose)),1]
    SecondDose_subset1 <- SecondDose[j:nrow(SecondDose),1]
    dist_SecondDose <- proxy::dist(t(FirstDose_subset1), t(SecondDose_subset1), method = "Minkowski", p = p)
    dist_vector = c(dist_vector, dist_SecondDose)
    j = j + 1
  }
  
  # select min value index which corresponds to value of the lag
  return(which.min(dist_vector))
}  
```


```{r}
lag_vector_1 <- c()
lag_vector_2 <- c()
lag_vector_3 <- c()
# loop through each country and calculate 3 time lags: manhattan distance, euclidean distance and minkowski (p=3) time lags
p = 1
while (p <= 3){
  z = 1
  while (z <= length(countries)){
    # only select records for certain country and only select 1st and 2nd vaccine columns
    lagCovid_filtered = filter(lag_covid, location == countries[z])
    combined_matrix <- cbind(lagCovid_filtered[,3], lagCovid_filtered[,4])
    
    # In the dataset, there are missing values. Will replace these missing values (0) with the value from the date before. Do it for both 1st and 2nd vaccine columns
    
    for (i in 1:nrow(combined_matrix)){
      if (i == 1){
        } else{
        if (combined_matrix[i,1] == 0){
          combined_matrix[i,1] = combined_matrix[i-1, 1]
        }
      }
    }
    
    for (j in 1:nrow(combined_matrix)){
      if (j == 1){
        } else{
        if (combined_matrix[j,2] == 0){
          combined_matrix[j,2] = combined_matrix[j-1, 2]
        }
      }
    }
    
    # Apply smoothing function to 1st and 2nd vaccine columns. f = 0.15 is an arbitrary value
    
    combined_matrix_smooth<- as.matrix(apply(combined_matrix, 2, Lowess, f = 0.15))
    
    # Store each column separately as individual matrices
    FirstDose_matrix = as.matrix(combined_matrix_smooth[,1])
    SecondDose_matrix = as.matrix(combined_matrix_smooth[,2])
  
    # Graph the 1st and 2nd vaccine percentages as a figure of interest. Need to convert back to dataframe.
    # X axis is in days
    # combined_matrix_smooth_df = as.data.frame(combined_matrix_smooth)
    # matplot(cbind(combined_matrix_smooth_df[,1], combined_matrix_smooth_df[,2]), type ="l", lty = 1, ylab = "Percentage of Population", xlab = countries[z])
    # legend("topleft", c("At Least 1 Vaccine", "2 Vaccines"), lty = 1, col=1:2)
    
    # Input the individual matrices into the lagValue function to find the lag between the 1st and 2nd dose for a particular country
    lag <- lagValue(FirstDose_matrix, SecondDose_matrix, windowsize=100, p)
    
    #store value of lag
    if (p == 1){
      lag_vector_1 <- c(lag_vector_1, lag)
    } else if (p == 2){
      lag_vector_2 <- c(lag_vector_2, lag)
    } else {
      lag_vector_3 <- c(lag_vector_3, lag)
    }
    z = z + 1
  }
  p = p + 1
}
# label the lag values with the corresponding country
names(lag_vector_1) <- countries
names(lag_vector_2) <- countries
names(lag_vector_3) <- countries
```



```{r}
# function to explain the time lag value

lagType <- function(lag, windowsize)
{ # Function to convert indice value given by lagValue to a value for the Time Lag.
  # Any lag values that are greater than windowsize were part of the 2nd half of the 'dist_vector' from the lagValue function, the half of the vector for the 2nd vaccine lag.
  # Therefore need to subtract off all the days from the 1st half of the 'dist_vector' to get number of days for 2nd vaccine lag.
  # No such issue for 1st vaccine lag as all values are within first half.
  if (lag > windowsize){
    return(c(LagType = "Second Dose Lag", Lag = lag - windowsize - 1))
  } else {
    return(c(LagType = "First Dose Lag", Lag = lag - 1))
  }
}
# Apply function to each countries Time lag value 
lag_df_1 = mapply(lagType, lag = lag_vector_1, windowsize = 100)
lag_df_2 = mapply(lagType, lag = lag_vector_2, windowsize = 100)
lag_df_3 = mapply(lagType, lag = lag_vector_3, windowsize = 100)

# Visualise Time lags

total_lag = cbind(t(lag_df_1), t(lag_df_2), t(lag_df_3))
colnames(total_lag) = c("LagType", "Lag: Euclidean distance", "LagType", "Lag: Manhattan distance", "LagType", "Lag: Minkowksi distance (P=3)")
datatable(total_lag, options = list(columnDefs = list(list(className = 'dt-center', targets = "_all"))))
```



```{r}
# Plot 1/3 of countries time lags: using euclidean distance time lag

# Convert time lag table to dataframe, get required tables, convert time lag to numeric
lag_table_1 = as.data.frame(t(lag_df_1))
lag_table_1 <- cbind(Country = rownames(lag_table_1), lag_table_1)
lag_table_1$Lag = as.numeric(lag_table_1$Lag) 
lag_table_11 = lag_table_1[1:(nrow(lag_table_1)/3),]

# plot the lag 
fig_1 = plot_ly(data = lag_table_11, x = ~Country, y = ~Lag, type = 'bar')
fig_1 = fig_1 %>% layout(title = "Lag Between 1st and 2nd COVID-19 Vaccine")
fig_1
```


```{r}
# Plot 2/3 countries time lags

lag_table_12 = lag_table_1[(nrow(lag_table_1)/3 + 1):(nrow(lag_table_1)*(2/3)),]
fig_2 = plot_ly(data = lag_table_12, x = ~Country, y = ~Lag, type = 'bar')
fig_2 = fig_2 %>% layout(title = "Lag Between 1st and 2nd COVID-19 Vaccine")
fig_2
```

```{r}
# Plot 3/3

lag_table_13 = lag_table_1[(nrow(lag_table_1)*(2/3)+1):nrow(lag_table_1),]
fig_3 = plot_ly(data = lag_table_13, x = ~Country, y = ~Lag, type = 'bar')
fig_3 = fig_3 %>% layout(title = "Lag Between 1st and 2nd COVID-19 Vaccine")
fig_3
```


```{r, warning = False}
# Box plots of time lags for all 3 types of time lags measurements

total_lag_df <- as.data.frame(total_lag)
colnames(total_lag_df) = c("LagType", "LagEuclideanDistance", "LagType", "LagManhattanDistance","LagType", "LagMinkowskiDistanceP3")

box <- plot_ly(type = "box")
box <- box %>% add_boxplot(x = total_lag_df$LagManhattanDistance, boxpoints = "all", jitter = 0.3, name = "Manhattan Distance")
box <- box %>% add_boxplot(x = total_lag_df$LagEuclideanDistance, boxpoints = "all", jitter = 0.3, name = "Euclidean Distance")
box <- box %>% add_boxplot(x = total_lag_df$LagMinkowskiDistanceP3, boxpoints = "all", jitter = 0.3, name = "Minkowski Distance (P=3)")
box <- box %>% layout(title = "Box Plot of Lag Between 1st and 2nd Dose")
box

```

## Analysing whether choosing different time periods affects the value of time lag. Calculating, for each country, standard deviation of time lags to see if results are volatile

```{r}
lag_covid = covid
standard_dev <- c()
# looping through each country
for (countryz in countries){
    # cleaning, filtering and prepping data for time lag calculation
    country_lag = covid %>%
    filter(location == countryz) %>%
    select(date, people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred)
    country_lag$people_vaccinated_per_hundred[is.na(country_lag$people_vaccinated_per_hundred)] = 0
    country_lag$people_fully_vaccinated_per_hundred[is.na(country_lag$people_fully_vaccinated_per_hundred)] = 0
    for (i in 1:nrow(country_lag)){
        if (i == 1){
          } else{
          if (country_lag$people_vaccinated_per_hundred[i] == 0){
            country_lag$people_vaccinated_per_hundred[i] = country_lag$people_vaccinated_per_hundred[i-1]
          }
        }
      }
      
    for (j in 1:nrow(country_lag)){
        if (j == 1){
          } else{
          if (country_lag$people_fully_vaccinated_per_hundred[j] == 0){
            country_lag$people_fully_vaccinated_per_hundred[j] = country_lag$people_fully_vaccinated_per_hundred[j-1]
          }
        }
      }
    country_lag <- country_lag %>%
    filter(people_vaccinated_per_hundred > 0)
    country_lag$people_vaccinated_per_hundred <- Lowess(country_lag$people_vaccinated_per_hundred, f = 0.15)
    country_lag$people_fully_vaccinated_per_hundred <- Lowess(country_lag$people_fully_vaccinated_per_hundred, f = 0.15)
    for (i in 1:nrow(country_lag)){
      if (country_lag$people_vaccinated_per_hundred[i] < 0){
        country_lag$people_vaccinated_per_hundred[i] = 0
      }
      if (country_lag$people_fully_vaccinated_per_hundred[i] < 0){
        country_lag$people_fully_vaccinated_per_hundred[i] = 0
      }
    }
    window = 150
    o = 1
    lag_country = c()
    # rolling windows of the data and calculate time lag for each window
    while ((o + window) <= nrow(country_lag)){
      subset <- country_lag[o:(o+window),] %>%
        select(people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred)
      FirstDose_matrix = as.matrix(subset$people_vaccinated_per_hundred)
      SecondDose_matrix = as.matrix(subset$people_fully_vaccinated_per_hundred)
      lag <- lagValue(FirstDose_matrix, SecondDose_matrix, windowsize=100, 2)
      lag_country <- c(lag_country, lag)
      o = o + 30
      }
    for (i in 1:length(lag_country)){
      if (lag_country[i] > 100){
        lag_country[i] = lag_country[i] - 100 -1
      } else {
          lag_country[i] = lag_country[i] -1
        }
        
    }
    # calculate standard deviation of time lags and store in vector
    standard_dev <- c(standard_dev, sd(lag_country))
}
#standard_dev
```

Clearly the results fluctuate based on time period as seen below.

```{r}
boxy <- plot_ly(type = "box")
boxy <- boxy %>% add_boxplot(x = standard_dev, boxpoints = "all", jitter = 0.3, name = "Time Lag StDevs for each country")
boxy
```




