---
title: "vri"
author: "Xinzhi Wang"
date: '2022-05-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(tibble)
library(ggplot2)
library(ggthemes)
library(maps)

library(plotly) # Interactive data visualizations
library(viridis) # Color gradients
library(lubridate)

library(randomForest) 
library(ranger)       # a faster implementation of randomForest
library(caret)        # performe many machine learning models
library(broom)  # try: `install.packages("backports")` if diretly installing broom gives an error

library(reshape2) # to use melt()

library(deSolve)
```


```{r}
covid <- read.csv("owid-covid-data.csv")
covid$date <- as.Date(covid_data$date, format = "%d/%m/%y")
#head(covid_data)
```

```{r}
data <- covid[covid$location == "United States", ] %>%
  filter(!is.na(people_vaccinated) & people_vaccinated != 0) %>%
  filter(!is.na(total_vaccinations) & total_vaccinations != 0) %>%
  select(location, date, people_vaccinated, total_vaccinations, population)

data$index <- c(1:length(data$people_vaccinated))
```

```{r}
SS <- getInitial(data$total_vaccinations ~ SSlogis(data$index, alpha, xmid, scale), data = data)

K_start <- SS["alpha"]
R_start <- 1/SS["scale"]
N0_start <- SS["alpha"]/(exp(SS["xmid"]/SS["scale"])+1)
```

```{r}
log_formula <- formula(data$total_vaccinations ~ K*N0*exp(R*data$index)/(K + N0*(exp(R*data$index) - 1)))


formu<-nls(log_formula, data = data, start = list(K = K_start, R = R_start, N0 = N0_start))
```

r is the intrinsic growth rate
```{r}
summary(formu)

r = summary(formu)$coefficients[[2]]
```



```{r}
ggplot(data,aes(index,predict(formu)))+geom_line()+
  geom_point(aes(y=total_vaccinations))+
  theme_bw()+
  theme(panel.grid.minor = element_blank(),panel.grid.major = element_blank())+xlab("Fermentation days")+ylab("Dry weight of biomass (mg)")

```


```{r}
RSQUARE = function(y_actual,y_predict){
  cor(y_actual,y_predict)^2
}

# RSQUARE(data$total_vaccinations, predict(formu))
```



vri
```{r}
vri <- r * (data$total_vaccinations[length(data$total_vaccinations)]) / data$population[1]
```


```{r}
estimate_r <- function(data){

data$index <- c(1:length(data$total_vaccinations))

  SS <- getInitial(data$total_vaccinations ~ SSlogis(data$index, alpha, xmid, scale), data = data)

  K_start <- SS["alpha"]
  R_start <- 1/SS["scale"]
  N0_start <- SS["alpha"]/(exp(SS["xmid"]/SS["scale"])+1)
  
  log_formula <- formula(data$total_vaccinations ~ K*N0*exp(R*data$index)/(K + N0*(exp(R*data$index) - 1)))
  
  
  formu<-nls(log_formula, data = data, start = list(K = K_start, R = R_start, N0 = N0_start))
  
  return(formu)
}
```


```{r}
estimate_vri <- function(data, r){
  vri <- r * (data$total_vaccinations[length(data$total_vaccinations)]) / data$population[1]
  
  return(vri)
}
```


```{r}
# countries_data <- covid %>%
#   filter(!is.na(people_vaccinated) & people_vaccinated != 0) %>%
#   filter(!is.na(total_vaccinations) & total_vaccinations != 0) %>%
#   select(location, date, people_vaccinated, total_vaccinations, population, aged_65_older, gdp_per_capita, cardiovasc_death_rate, handwashing_facilities, hospital_beds_per_thousand, human_development_index)

# countries = c("United States", "India", "Brazil", "France", "United Kingdom", "Russia",
#               "Turkey", "Italy", "Germany", "Spain", "Argentina",
#                 "Iran", "Colombia", "Poland", 'Mexico', "Netherlands",
#               "Indonesia", "Ukraine", "South Africa", "Peru", "Belgium",
#                 "Czechia", "Japan", "Israel")

countries <- unique(covid$location)

vri_data <- NULL
avg <- 0
count <- 0

for (c in countries) {
  print(c)
  if (c %in% c("Afghanistan", "Antigua and Barbuda", "Bhutan", "Bonaire Sint Eustatius and Saba", "Botswana", "Cameroon", "Cote d'Ivoire", "Democratic Republic of Congo", "Ethiopia", "Eritrea", "Gabon", "Ghana", "Guernsey", "Guinea", "Kenya", "Kuwait", "Liberia", "Marshall Islands", "Micronesia (country)", "Namibia", "Nepal", "Niger", "Nigeria", "Palau", "Palestine", "Philippines", "Pitcairn", "Puerto Rico", "Rwanda", "Saint Helena", "Saint Pierre and Miquelon", "Senegal", "Somalia", "South Sudan", "Sudan", "Tokelau", "Turkmenistan", "Uganda", "Vatican", "World", "Zambia", "International")) {
    next
  }
  country <- covid[covid$location == c, ] %>%
  filter(!is.na(people_vaccinated) & people_vaccinated != 0) %>%
  filter(!is.na(total_vaccinations) & total_vaccinations != 0) %>%
  select(location, date, people_vaccinated, total_vaccinations, population)
  
  formu <- estimate_r(country)
  
  avg <- avg +  RSQUARE(country$people_vaccinated, predict(formu))
  count <- count + 1
  
  r <- summary(formu)$coefficients[[2]]
  
  vri <- estimate_vri(country, r)
  
  
  temp <- data.frame(location = c, vri = vri, 
                     aged_65_older = covid[covid$location == c, ]$aged_65_older[1], 
                     gdp_per_capita = covid[covid$location == c, ]$gdp_per_capita[1], 
                     cardiovasc_death_rate = covid[covid$location == c, ]$cardiovasc_death_rate[1], 
                     handwashing_facilities = covid[covid$location == c, ]$handwashing_facilities[1], 
                     hospital_beds_per_thousand = covid[covid$location == c, ]$hospital_beds_per_thousand[1], 
                     human_development_index = covid[covid$location == c, ]$human_development_index[1])

  vri_data <- rbind(vri_data, temp)
}

avg / count
```

```{r}
# Create a Random Forest model with default parameters

vri_data <- vri_data %>%
  drop_na()

min_max_norm <- function(x) {
    (x - min(x)) / (max(x) - min(x))
}

temp_data <- data.frame(lapply(vri_data[3:8], min_max_norm), vri = vri_data$vri)


rf <- train(vri ~ ., data= temp_data, method = "rf", ntree=500, importance=TRUE, seed=1)


# rf <- randomForest(vri ~ ., data = temp_data, ntree = 500, importance = TRUE, seed = 2)
```


```{r}
varImpPlot(rf, main = "variable importance")
```


```{r}
temp <- temp_data %>%
  select(-vri)

result <- predict(rf, newdata=temp)
result_avg <- mean(result)

1 - (sum((vri_data$vri - result)^2))/(sum((vri_data$vri - result_avg)^2))

```


```{r}
ggplot(data = vri_data, aes(x=vri, y=gdp_per_capita)) + geom_point() + ggtitle("GDP per capita vs Vaccine Roll-out Index(vri)")
ggplot(data = vri_data, aes(x=vri, y=human_development_index)) + geom_point() + ggtitle("human_development_index vs Vaccine Roll-out Index(vri)")
```




