---
title: "Avalability"
author: "Xinzhi Wang"
date: '2022-05-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

#install.packages("RSpectra")
#install.packages("stringdist")
#install.packages("viridis")
install.packages("hrbrthemes")

```



```{r cars}
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggthemes)
library(maps)
library(DT)
library(RSpectra)
library(GEOquery) 
library(R.utils)
library(tuneR)
library(randomForest)
library(stringdist)
library(plotly)
library(viridis)
library(hrbrthemes)
libraru()
```

# Load Data
```{r}
covid <- read.csv("owid-covid-data.csv")
policy <- read.csv("covid-vaccination-policy.csv")
```


```{r}
countries = c("United States", "India", "Brazil", "France", "United Kingdom", "Russia", 
              "Turkey", "Italy", "Germany", "Spain", "Argentina",
                "Iran", "Colombia", "Poland", 'Mexico', "Netherlands", 
              "Indonesia", "Ukraine", "South Africa", "Philippines", "Peru", "Belgium",
                "Czechia", "Japan", "Israel")


covid <- covid %>% filter(location %in% countries)
policy <- policy %>% filter(Entity %in% countries)
```

```{r}
merged_data <- covid %>% 
  select(iso_code, continent, location, date, total_vaccinations, total_vaccinations_per_hundred,new_people_vaccinated_smoothed_per_hundred,  new_people_vaccinated_smoothed, new_vaccinations, new_vaccinations_smoothed, new_vaccinations_smoothed_per_million, total_boosters, population, people_vaccinated)
merged_data <- merge(data, policy, by.x = c('iso_code', "date", "location"), by.y = c('Code', 'Day', "Entity"))
```

```{r}
avaliable <- function(data, country) {
  country_data <- data[data$location == country, ]
  
  country_policy <- country_data %>%
    group_by(vaccination_policy) %>%
    arrange(date) %>% 
    slice(1L) %>%
    select(iso_code, location, date, vaccination_policy, new_vaccinations_smoothed, population, people_vaccinated)
  
    scale <- (max(country_data$people_vaccinated[!is.na(country_data$people_vaccinated)]) / country_data$population) / max(country_data$new_vaccinations_smoothed[!is.na(country_data$new_vaccinations_smoothed)])
  
  g <- ggplot() + 
    geom_point(data = country_data, aes(x = as.Date(date), y = new_vaccinations_smoothed, group = as.factor(vaccination_policy), color = as.factor(vaccination_policy))) +
    geom_line(data = country_data, aes(x = as.Date(date), y = people_vaccinated / (population * scale)), color = "darkblue", size = 1) + 
    scale_y_continuous(name = "New vaccination", sec.axis = sec_axis(~.*scale , name = "The ratio of people vaccinated")
    ) + geom_segment(data = country_policy, aes(x = as.Date(date), xend=as.Date(date), y =0, yend=new_vaccinations_smoothed, colour = as.factor(vaccination_policy)), size = 0.8) + 
    ggtitle(country) + 
    xlab("Date") + 
    labs(color = "Avalability stage")
  
  return(g)
}



```

```{r}
country_data <- data[data$location == "United States", ]
  
  country_policy <- country_data %>%
    group_by(vaccination_policy) %>%
    arrange(date) %>% 
    slice(1L) %>%
    select(iso_code, location, date, vaccination_policy, new_vaccinations_smoothed, population, people_vaccinated)
```

```{r}
ggplot(data = country_data, aes(x = as.Date(date))) + 
  geom_point(aes(y = new_vaccinations_smoothed, group = vaccination_policy, color = as.factor(vaccination_policy))) +
  geom_line(aes(y = (total_vaccinations - total_boosters)  / population)) + 
  scale_y_continuous(sec.axis = sec_axis(~ . / 10000000, name = "")
  )
```

#filtering and cleaning the data
```{r}

#filtering and cleanng the data
#Make all na 0 and rename some variables
merged_data$new_vaccinations_smoothed[is.na(merged_data$new_vaccinations_smoothed)] = 0
merged_data <- rename(merged_data, vaccination_policy = vaccination_policy.x)
merged_data$vaccination_policy.y <- NULL

merged_data
```
```{r}
# convert suitable  data types
merged_data$location <- as.character(merged_data$location)
merged_data$vaccination_policy <- as.factor(merged_data$vaccination_policy)
merged_data
```

Subsetting data
```{r}
glimpse(merged_data)

clean_data <- merged_data %>%
  select(iso_code, location, date, new_vaccinations_smoothed, vaccination_policy)

#clean_data$new_vaccinations_smoothed[is.na(clean_data$new_vaccinations_smoothed)] = 0
clean_data
```

More data wrangling
```{r}
filterdata <- clean_data %>%
  group_by(location, vaccination_policy) %>%
  summarize(new_vaccine_smooth = sum(new_vaccinations_smoothed))

filterdata
```



Graph of all the countries at different stages
```{r}

filterdata %>%
  ggplot(aes(fill = vaccination_policy, y = new_vaccine_smooth, x = location)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_viridis(discrete = T) +
  ggtitle("Vaccination stage of each country") +
  facet_wrap(~vaccination_policy, scales = "free_y") +
  theme(axis.text.x = element_text(size = rel(0.5),angle = 90, vjust = 1, hjust = 1)) +
  scale_y_continuous(limits = c(0,1200000000)) 







```


Graph of individual countries
```{r}


filterdata %>%
  ggplot(aes(fill = vaccination_policy, y = new_vaccine_smooth, x = location)) +
  geom_bar(position="stack", stat="identity") +
  scale_fill_viridis(discrete = T) +
  ggtitle("Vaccination stage of each country") +
  facet_wrap(~vaccination_policy, scales = "free_y") +
  theme(axis.text.x = element_text(size = rel(0.5),angle = 90, vjust = 1, hjust = 1)) +
  scale_y_continuous(limits = c(0,1200000000)) 








```







Subsetting the data for France as an example 
```{r}



filterdata1 <- filterdata[filterdata$location == "France",]

p <- filterdata1 %>%
  mutate(filterdata1, vaccination_policy = as.numeric(vaccination_policy)) %>%
  ggplot(aes(y = new_vaccine_smooth, x = vaccination_policy)) +
  geom_point(shape=21, color="black", fill="#69b3a2", size=2) +
  geom_line(colour = "grey") +
  scale_x_continuous(limits = c(0,5)) +
  #geom_bar(position = "stack", stat = "identity") +
  #geom_line( color="#69b3a2", size=2, alpha=0.9, linetype=2) +
  scale_fill_viridis(discrete = T) +
  ggtitle("France vaccination stage") 

p
```
Another example using Bar plot
```{r}



filterdata1 <- filterdata[filterdata$location == "France",]

p1 <- filterdata1 %>%
  ggplot(aes(y = new_vaccine_smooth, x = vaccination_policy, colour = vaccination_policy, fill = vaccination_policy)) +
  geom_bar(position = "stack", stat = "identity") +
  geom_point() + geom_line() +
  scale_fill_viridis(discrete = T) +
  scale_color_viridis(discrete=TRUE) +
  ggtitle("France vaccination stage") 

p1
```

Calculate the speed, which is pretty much the graduet
```{r}

francespeed <- diff(filterdata1$new_vaccine_smooth)/diff(filterdata1$vaccination_policy)
francespeed

```
```{r}
avaliable <- function(data, vaccination) {
  country_data <- data[data$location == country, ]
  
  country_policy <- country_data %>%
    group_by(vaccination_policy) %>%
    arrange(date) %>% 
    slice(1L) %>%
    select(iso_code, location, date, vaccination_policy, new_vaccinations_smoothed, population, people_vaccinated)
  
    scale <- (max(country_data$people_vaccinated[!is.na(country_data$people_vaccinated)]) / country_data$population) / max(country_data$new_vaccinations_smoothed[!is.na(country_data$new_vaccinations_smoothed)])
  
  g <- ggplot() + 
    geom_point(data = country_data, aes(x = as.Date(date), y = new_vaccinations_smoothed, group = as.factor(vaccination_policy), color = as.factor(vaccination_policy))) +
    geom_line(data = country_data, aes(x = as.Date(date), y = people_vaccinated / (population * scale)), color = "darkblue", size = 1) + 
    scale_y_continuous(name = "New vaccination", sec.axis = sec_axis(~.*scale , name = "The ratio of people vaccinated")
    ) + geom_segment(data = country_policy, aes(x = as.Date(date), xend=as.Date(date), y =0, yend=new_vaccinations_smoothed, colour = as.factor(vaccination_policy)), size = 0.8) + 
    ggtitle(country) + 
    xlab("Date") + 
    labs(color = "Avalability stage")
  
  return(g)
}







```






```{r}
merged_data %>%
  ggplot(aes_(x = country, new_vaccinations_smoothed, group = location)) +
  geom_point()







```


```{r}
ggplot() + geom_line(data = country_data, aes(x = as.Date(date), y = (total_vaccinations - total_boosters) / population))
```


```{r}
ggplot() + geom_line(data = country_data, aes(x = as.Date(date), y = people_vaccinated * 100 / population)) +
  geom_vline(data = country_policy, aes(xintercept = as.Date(date), color = as.factor(vaccination_policy)))
```



```{r}
scale <- (max(country_data$people_vaccinated[!is.na(country_data$people_vaccinated)]) / country_data$population) / max(country_data$new_vaccinations_smoothed[!is.na(country_data$new_vaccinations_smoothed)])

ggplot() + 
  geom_point(data = country_data, aes(x = as.Date(date), y = new_vaccinations_smoothed, group = as.factor(vaccination_policy), color = as.factor(vaccination_policy))) +
  geom_line(data = country_data, aes(x = as.Date(date), y = people_vaccinated / (population * scale)), color = "darkblue", size = 1) + 
  scale_y_continuous(name = "New vaccination", sec.axis = sec_axis(~.*scale , name = "The ratio of people vaccinated")
  ) + geom_segment(data = country_policy, aes(x = as.Date(date), xend=as.Date(date), y =0, yend=new_vaccinations_smoothed, colour = as.factor(vaccination_policy)), size = 0.8) + 
  ggtitle("United States") + 
  xlab("Date") + 
  labs(color = "Avalability stage")
```



```{r}
avaliable(data, "United States")
```



```{r}



ggplot(data)



```
















